### ISSUE TITLE
Handle zstd compressed rpms

### ISSUE THREAD

**Issue by netjunki** [srossross/rpmfile#30]
Was trying out this module to help a friend with a question they had and discovered that it didn't work with some of the rpms I tried it with. After a little bit of digging I managed to figure out that the reason was the use of an unsupported compression scheme.

Here's one which exhibits the issue: http://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/x/xmlstarlet-1.6.1-14.fc32.x86_64.rpm

You can extract the metadata from these but when you go to extract files you get an error like this:

    Traceback (most recent call last):
      File "processrpm.py", line 32, in <module>
        for member in rpm.getmembers():
      File "/usr/local/lib/python3.7/site-packages/rpmfile/__init__.py", line 119, in getmembers
        magic = g.read(2)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 287, in read
        return self._buffer.read(size)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_compression.py", line 68, in readinto
        data = self.read(len(byte_view))
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 474, in read
        if not self._read_gzip_header():
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 422, in _read_gzip_header
        raise OSError('Not a gzipped file (%r)' % magic)
    OSError: Not a gzipped file (b'(\xb5')

I tried [adapting rpmfile](https://github.com/srossross/rpmfile/compare/master...netjunki:zstd-support) with a small patch to add support for zstd compression, but ran into another issue due to zstd not supporting backwards seeks:

    Traceback (most recent call last):
      File "processrpm.py", line 49, in <module>
        efile.write(fd.read())
      File "/usr/local/lib/python3.7/site-packages/rpmfile/io_extra.py", line 76, in read
        self._fileobj.seek(self._pos + self._start, 0)
    ValueError: cannot seek zstd decompression stream backwards

But that was about as far as I've been able to take this so thought a bug report might be helpful.

**Comment by pdxjohnny** [comment]
Thanks for reporting!

**Comment by pdxjohnny** [comment]
Mirroring here since rawhide URL might go away

[xmlstarlet-1.6.1-14.fc32.x86_64.txt.gz](https://github.com/srossross/rpmfile/files/4505086/xmlstarlet-1.6.1-14.fc32.x86_64.txt.gz)

**Comment by pdxjohnny** [comment]
@netjunki support for zstd rpms is in `1.0.2`, you'll just need to be running Python >= 3.5 (since I used `io.BytesIO` to just read the whole thing into memory)

```console
$ python -m pip install -U rpmfile zstandard
```

**Comment by netjunki** [comment]
@pdxjohnny Thanks so much! Works like a charm.

**Comment by pdxjohnny** [comment]
No problem! Great to hear! :D
