### ISSUE TITLE
rpmfile fails to load localized RPM headers

### ISSUE THREAD

**Issue by epowell** [srossross/rpmfile#6]
For packages with string data in multiple languages, rpmfile produces the following error:

```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpmfile
>>> f = rpmfile.open('~/Downloads/nagios-3.5.1-1.el7.x86_64.rpm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rpmfile/__init__.py", line 168, in open
    return RPMFile(name, mode, fileobj)
  File "/usr/local/lib/python2.7/dist-packages/rpmfile/__init__.py", line 79, in __init__
    self._header_range, self._headers = get_headers(self._fileobj)
  File "/usr/local/lib/python2.7/dist-packages/rpmfile/headers.py", line 189, in get_headers
    return _readheader(fileobj)
  File "/usr/local/lib/python2.7/dist-packages/rpmfile/headers.py", line 177, in _readheader
    value = extract_data(ty, offset, count, store)
  File "/usr/local/lib/python2.7/dist-packages/rpmfile/headers.py", line 139, in extract_data
    return extract(offset, count, store)
  File "/usr/local/lib/python2.7/dist-packages/rpmfile/headers.py", line 99, in extract_string
    assert count == 1
AssertionError
>>> 
```

Debugging using this diff tells us that localization within the header is the issue:

```
--- headers.py  2016-01-28 14:56:43.029763579 -0600
+++ headers.py.new      2016-01-28 14:56:35.565763899 -0600
@@ -96,6 +96,8 @@


 def extract_string(offset, count, store):
+    if count > 1:
+        return extract_array(offset, count, store)
     assert count == 1
     idx = store[offset:].index(b'\x00')
     return store[offset:offset + idx]
```

```
>>> f = rpmfile.open('/home/epowell/Downloads/nagios-4.0.8-2.el7.x86_64.rpm')                                                                                                                                
>>> f.headers['summary']
['Host/service/network monitoring program', 'Nagios \xc3\xbccht Dienste und Rechner und meldet Ihnen Ausf\xc3\xa4e']
>>> f.headers['description']                                                                                                                                                                                 
['Nagios is a program that will monitor hosts and services on your\nnetwork.  It has the ability to send email or page alerts when a\nproblem arises and when a problem is resolved.  Nagios is written\nin $
 and is designed to run under Linux (and some other *NIX\nvariants) as a background process, intermittently running checks\non various services that you specify.\n\nThe actual service checks are performed 
by separate "plugin" programs\nwhich return the status of the checks to Nagios. The plugins are\navailable at https://github.com/nagios-plugins/nagios-plugins\n\nThis package provides the core program, we$
 interface, and documentation\nfiles for Nagios. Development files are built as a separate package.', '', 'Nagios ist ein Programm zum \xc3\x9cberwachen von Rechner und Diensten\nin Ihrem Netzwerk. Wenn e$
was ausf\xc3\xa4llt, kann es Sie per eMail\noder Pager benachrichtigen. Nagios ist in C geschrieben und\nsollte auf allen Unix-Varianten (inklusive Linux :-) laufen. Es\nl\xc3\xa4uft als D\xc3\xa4mon und $
xc3\xbcberwacht laufend alle konfigurierten\nDienste.\n\nNagios \xc3\xbcberpr\xc3\xbcft die Rechner und Dienste nicht selber, sondern\nbraucht daf\xc3\xbcr externe Programme. Viele dieser Programme finden$
nSie im Paket nagios-plugins.']
>>> 
```

Fix options:
1. Return the array instead of a string, allowing the user of the library to deal with the localized versions. This would break compatibility with those expecting a single string.
2. Return the first element of the array. This would lock the library in to only the first localized string for a package, which may not be the behavior desired for all packages.
3. Investigate RPM's localization and choose a return string based on the machines (or the requested) locale.

**Comment by pdxjohnny** [comment]
@MarsCapone @benchalmers @tseemann would you all be interested in opening a PR to get the changes you have upstream? If you don't have time, do we have your permission to merge in that stuff under the MIT license?

**Comment by leifliddy** [comment]
I'm running into this exact same issue trying to open this centos7 rpm
```
qrencode-libs-3.4.1-3.el7.x86_64.rpm
```
I receive the following error:
```  File "/usr/local/lib/python3.6/site-packages/rpmfile/__init__.py", line 208, in open
    return RPMFile(name, mode, fileobj)
  File "/usr/local/lib/python3.6/site-packages/rpmfile/__init__.py", line 103, in __init__
    self._header_range, self._headers = get_headers(self._fileobj)
  File "/usr/local/lib/python3.6/site-packages/rpmfile/headers.py", line 407, in get_headers
    second_range, second_headers = _readheader(fileobj)
  File "/usr/local/lib/python3.6/site-packages/rpmfile/headers.py", line 394, in _readheader
    value = extract_data(ty, offset, count, store)
  File "/usr/local/lib/python3.6/site-packages/rpmfile/headers.py", line 355, in extract_data
    return extract(offset, count, store)
  File "/usr/local/lib/python3.6/site-packages/rpmfile/headers.py", line 315, in extract_string
    assert count == 1
AssertionError
```
MarsCapone's fix works. Can this this change be commited?

**Comment by micrenda** [comment]
Could someone please merge this fix? It would be useful when reading RPM like autofs-5.1.4-40.el8.x86_64.rpm that seems that can not be read with the current rpmfile.

**Comment by pdxjohnny** [comment]
@leifliddy @micrenda Well it only took 7ish years but I think the fix is in https://github.com/srossross/rpmfile/releases/tag/2.0.0 please let us know if that resolves your issue :P

**Comment by micrenda** [comment]
wow.... this was a very fast feedback! :-)

I will check and come with a feedback asap!

**Comment by micrenda** [comment]
I have never been so happy to delete some code that I just wrote. Your fix was very helpful and solved the issue.
Thank you very much for the great support!

From my point of view, this ticket can be marked as resolved!

**Comment by pdxjohnny** [comment]
Woohoo!! i just happened to see the github notification email at the right time. :) glad it’s working
