### ISSUE TITLE
 import rpmfile problem 

### ISSUE THREAD

**Issue by patelp23** [srossross/rpmfile#9]
```
import rpmfile
```

  File "C:\Python26\lib\site-packages\rpmfile__init__.py", line 3, in <module>
    from .headers import get_headers
  File "C:\Python26\lib\site-packages\rpmfile\headers.py", line 95
    rtags = {value:key for (key, value) in tags.items()}
                         ^
SyntaxError: invalid syntax

**Comment by NGSegovia** [comment]
Also not works in Linux:

`>>> import rpmfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/rpmfile/__init__.py", line 3, in <module>
    from headers import get_headers
  File "/usr/lib/python2.6/site-packages/rpmfile/headers.py", line 93
    rtags = {value:key for (key, value) in tags.items()}
                         ^
SyntaxError: invalid syntax`

**Comment by NGSegovia** [comment]
Version 0.1.1 works ok.

**Comment by pdxjohnny** [comment]
Closed by a5928999123922263b1e68ecdfe01ee01972d53c
